[versions]
apiguardian = "1.1.2"
junit-jupiter = "6.0.2"
junit-platform = "6.0.2"
assertJ = '3.27.7'
kotlin = '2.3.10'
#opentest4j = '1.3.0'
#archunit = '1.3.0'
#mockito = '5.14.2'

[libraries]
apiguardian = { module = "org.apiguardian:apiguardian-api", version.ref = "apiguardian" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertJ" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

# Used in conventions plug-ins:
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

# Used indirectly in gradle plugins build.gradle.kts:
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-powerAssertPlugin = { module = "org.jetbrains.kotlin:kotlin-power-assert", version.ref = "kotlin" }
